movie <- read.csv("C:/Users/guoshuhui/Desktop/Stat 448/project/moviedata.csv")
summary(movie$duration)
summary(movie$facenumber_in_poster)
summary(movie$budget)
summary(movie$title_year)
summary(movie$aspect_ratio)
summary(movie$imdb_score)
table(movie$score)
table(movie$color)
table(movie$genres)
table(movie$language)
table(movie$country)
table(movie$content_rating)
