proc import out=movie datafile="/home/clever_g0/Stat 448/moviedata.csv" dbms=csv replace;
    getnames=yes;
run;
proc logistic order = data data = movie plots=influence;
	class score color genres language country content_rating;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics1 cbar=cbar1;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics1;
    where cbar1>1;
run;
proc logistic order = data data = diagnostics1 plots=influence;
	class score color genres language country content_rating;
	where cbar1<150;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics2 cbar=cbar2;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics2;
    where cbar2>1;
run;
proc logistic order = data data = diagnostics2 plots=influence;
	class score color genres language country content_rating;
	where cbar2<1000;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics3 cbar=cbar3;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics3;
    where cbar3>1;
run;
proc logistic order = data data = diagnostics3 plots=influence;
	class score color genres language country content_rating;
	where cbar3<9000;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics4 cbar=cbar4;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics4;
    where cbar4>1;
run;
proc logistic order = data data = diagnostics4 plots=influence;
	class score color genres language country content_rating;
	where cbar4<9;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics5 cbar=cbar5;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics5;
    where cbar5>1;
run;
proc logistic order = data data = diagnostics5 plots=influence;
	class score color genres language country content_rating;
	where cbar5<1.6;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics6 cbar=cbar6;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics6;
    where cbar6>1;
run;
proc logistic order = data data = diagnostics6 plots=influence;
	class score color genres language country content_rating;
	where cbar6<1.2;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics7 cbar=cbar7;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics7;
    where cbar7>1;
run;
proc logistic order = data data = diagnostics7 plots=influence;
	class score color genres language country content_rating;
	where cbar7<1.1;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics8 cbar=cbar8;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics8;
    where cbar8>1;
run;
proc logistic order = data data = diagnostics8 plots=influence;
	class score color genres language country content_rating;
	where cbar8<1;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics9 cbar=cbar9;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics9;
    where cbar9>1;
run;
proc logistic order = data data = diagnostics9 plots=influence;
	class score color genres language country content_rating;
	where cbar9<20000;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics10 cbar=cbar10;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics10;
    where cbar10>1;
run;
proc logistic order = data data = diagnostics10 plots=influence;
	class score color genres language country content_rating;
	where cbar10<1;
	model score = color--title_year aspect_ratio / selection = stepwise;
	output out=diagnostics11 cbar=cbar11;
	ods select ModelBuildingSummary InfluencePlots;
run;
proc print data = diagnostics11;
    where cbar11>1;
run;
/* final model */
proc logistic order = data data = diagnostics10 plots=influence;
	class score genres country content_rating;
	where cbar10<1;
	model score = duration genres title_year content_rating country / lackfit;
	ods select FitStatistics GlobalTests LackFitChiSq ParameterEstimates OddsRatios;
run;
proc logistic order = data data = diagnostics10 plots=influence;
	class score genres content_rating;
	where cbar10<1;
	model score = duration genres title_year content_rating / lackfit;
	ods select FitStatistics GlobalTests LackFitChiSq ParameterEstimates OddsRatios InfluencePlots;
run;
/* roc curve and solve quasi-complete separation */
proc logistic order = data data = diagnostics10 plots=roc;
	class score genres content_rating;
	where cbar10<1;
	model score = duration genres title_year content_rating / lackfit;
	ods exclude InfluencePlots;
run;
/* confusion matrix */
proc logistic order = data data = diagnostics10;
    class score genres content_rating;
    where cbar10<1;
    model score = duration genres title_year content_rating / ctable pprob=0.5;
    output out=preds p=phat predprobs=individual;
run;
data ctable;
    set preds;
    if phat>=0.5 then test=1;
    else test=0;
run;
proc freq data = ctable;
    table score*test / norow nocol nopercent;
run;
/* classification table */
proc logistic order = data data = diagnostics10;
    class score genres content_rating;
    where cbar10<1;
    model score = duration genres title_year content_rating / ctable;
run;
/* confusion matrix after adjustment */
proc logistic order = data data = diagnostics10;
    class score genres content_rating;
	where cbar10<1;
	model score = duration genres title_year content_rating / ctable pprob=0.26;
    output out=preds2 p=phat2 predprobs=individual2;
run;
data ctable2;
    set preds2;
    if phat2>=0.26 then test=1;
    else test=0;
run;
proc freq data = ctable2;
    table score*test / norow nocol nopercent;
run;
